function test_part1_flow_wall_overrides()
%TEST_PART1_FLOW_WALL_OVERRIDES Verify Part1 flow and wall overrides propagate to Config.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    case_dir = fullfile(project_root, 'outputs', 'mat', 'test_part1_flow_wall_overrides');
    if exist(case_dir, 'dir') == 7
        rmdir(case_dir, 's');
    end
    mkdir(case_dir);

    old_dir = pwd;
    cleanup_obj = onCleanup(@() cd(old_dir)); %#ok<NASGU>
    cd(case_dir);

    Main_DoubleWedge_Part1_v6( ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'MachInf', 5.0, ...
        'ReInf', 2.5e5, ...
        'TInf', 250.0, ...
        'Gamma', 1.33, ...
        'Pr', 0.72, ...
        'WallModel', 'isothermal', ...
        'WallTemperature', 310.0);

    data = load('Part1_Results.mat', 'Config', 'BaseValidation');
    assert(abs(data.Config.Ma_inf - 5.0) < 1.0e-12, 'MachInf override did not reach Part1 Config.');
    assert(abs(data.Config.Re_inf - 2.5e5) < 1.0e-12, 'ReInf override did not reach Part1 Config.');
    assert(abs(data.Config.T_inf - 250.0) < 1.0e-12, 'TInf override did not reach Part1 Config.');
    assert(abs(data.Config.gamma - 1.33) < 1.0e-12, 'Gamma override did not reach Part1 Config.');
    assert(abs(data.Config.Pr - 0.72) < 1.0e-12, 'Pr override did not reach Part1 Config.');
    assert(strcmp(data.Config.wall_model, 'isothermal'), ...
        'WallModel override did not reach Part1 Config.');
    assert(abs(data.Config.T_wall - 310.0) < 1.0e-12, ...
        'WallTemperature override did not reach Part1 Config.');
    assert(abs(data.Config.T_wall_nd - 310.0 / 250.0) < 1.0e-12, ...
        'Part1 Config T_wall_nd should follow T_wall/T_inf.');
    assert(abs(data.Config.Cv_nd - 1.0 / (1.33 * (1.33 - 1.0) * 5.0^2)) < 1.0e-12, ...
        'Part1 Config Cv_nd should be recomputed after flow overrides.');
    assert(abs(data.Config.S_nd - 110.4 / 250.0) < 1.0e-12, ...
        'Part1 Config S_nd should be recomputed after flow overrides.');
    assert(strcmp(data.BaseValidation.wall_model, 'isothermal'), ...
        'BaseValidation should record the normalized wall model.');
    assert(data.BaseValidation.wall_temperature_check_applied, ...
        'Isothermal wall should enable the baseflow wall-temperature check.');

    fprintf('[test_part1_flow_wall_overrides] PASS\n');
end
