function test_paperA_pressure_row_regularization_v6()
%TEST_PAPERA_PRESSURE_ROW_REGULARIZATION_V6 Validate shock-localized pressure-row clipping.

    project_root = fileparts(fileparts(mfilename('fullpath')));
    addpath(project_root);
    addpath(fullfile(project_root, 'src', 'core'));

    shock_mask = logical([0; 0; 1; 1; 0; 0]);
    px_coeff = [1.0; 2.0; 100.0; -120.0; 3.0; 4.0];
    py_coeff = [2.0; -1.0; -80.0; 90.0; 3.0; -4.0];
    div_coeff = [0.10; -0.20; 30.0; -40.0; 0.30; -0.20];

    Config = struct();
    Config.pressure_row_regularization = struct( ...
        'enabled', true, ...
        'gradient_clip_percentile', 100.0, ...
        'divergence_clip_percentile', 100.0, ...
        'suppress_pressure_gradients_in_shock', false, ...
        'suppress_divergence_in_shock', false);

    [coeffs, audit] = build_paperA_pressure_row_regularization_v6( ...
        px_coeff, py_coeff, div_coeff, shock_mask, Config);

    assert(all(abs(coeffs.px(shock_mask)) <= 4.0 + 1.0e-12), ...
        'Shock-zone px coefficients should clip to the non-shock max abs value.');
    assert(all(abs(coeffs.py(shock_mask)) <= 4.0 + 1.0e-12), ...
        'Shock-zone py coefficients should clip to the non-shock max abs value.');
    assert(all(abs(coeffs.div(shock_mask)) <= 0.30 + 1.0e-12), ...
        'Shock-zone div coefficients should clip to the non-shock max abs value.');
    assert(audit.fields.px.num_clipped == 2 && audit.fields.py.num_clipped == 2 && audit.fields.div.num_clipped == 2, ...
        'Each weighted pressure-row field should report two clipped shock points.');

    Config.pressure_row_regularization.suppress_pressure_gradients_in_shock = true;
    Config.pressure_row_regularization.suppress_divergence_in_shock = true;
    [suppressed_coeffs, suppressed_audit] = build_paperA_pressure_row_regularization_v6( ...
        px_coeff, py_coeff, div_coeff, shock_mask, Config);
    assert(all(suppressed_coeffs.px(shock_mask) == 0.0) && all(suppressed_coeffs.py(shock_mask) == 0.0), ...
        'Pressure-gradient suppression should zero shock-zone px/py coefficients.');
    assert(all(suppressed_coeffs.div(shock_mask) == 0.0), ...
        'Divergence suppression should zero shock-zone div coefficients.');
    assert(suppressed_audit.fields.px.num_zeroed == 2 && suppressed_audit.fields.div.num_zeroed == 2, ...
        'Suppression should be visible in the saved audit counts.');

    Config.pressure_row_regularization.enabled = false;
    [raw_coeffs, raw_audit] = build_paperA_pressure_row_regularization_v6( ...
        px_coeff, py_coeff, div_coeff, shock_mask, Config);
    assert(isequal(raw_coeffs.px, px_coeff) && isequal(raw_coeffs.py, py_coeff) && isequal(raw_coeffs.div, div_coeff), ...
        'Disabling pressure-row regularization should return the raw coefficients unchanged.');
    assert(~raw_audit.enabled, 'Audit should record the disabled regularization state.');

    fprintf('[test_paperA_pressure_row_regularization_v6] PASS\n');
end
