function test_run_user_test_force_low_memory_descriptor_v6()
%TEST_RUN_USER_TEST_FORCE_LOW_MEMORY_DESCRIPTOR_V6 Ensure the runner can force the low-memory descriptor plan.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    case_name = 'test_run_user_test_force_low_memory_descriptor_v6';
    case_dir = fullfile(project_root, 'outputs', 'mat', case_name);
    if exist(case_dir, 'dir') == 7
        rmdir(case_dir, 's');
    end

    summary = run_user_test_baseflow_fullres_v6( ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'RunPart4', true, ...
        'NEigs', 6, ...
        'SigmaShift', 0.01 + 0.01i, ...
        'SigmaTriplet', 0.01 + 0.01i, ...
        'ForceLowMemoryDescriptor', true, ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false, ...
        'CaseName', case_name);

    part1 = load(fullfile(case_dir, 'Part1_Results.mat'), 'Config');
    assert(part1.Config.descriptor_solver.large_system_threshold == 1, ...
        'ForceLowMemoryDescriptor should force the large-system threshold down to 1.');

    part4 = load(fullfile(case_dir, 'Part4_Results.mat'), 'SolveAudit');
    assert(strcmp(part4.SolveAudit.memory_policy, 'large_system_low_memory'), ...
        'Forced low-memory runner path should mark SolveAudit.memory_policy as large_system_low_memory.');
    assert(strcmp(summary.stage_completed, 'Part4'), ...
        'Force-low-memory smoke case should still complete through Part4.');

    fprintf('[test_run_user_test_force_low_memory_descriptor_v6] PASS\n');
end
