function test_read_phenglei_multiline_zone_header()
%TEST_READ_PHENGLEI_MULTILINE_ZONE_HEADER Parse Tecplot headers split across lines.

    project_root = fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(project_root, 'run'));
    addpath(fullfile(project_root, 'src', 'core'));

    temp_root = tempname;
    mkdir(temp_root);
    cleanup_obj = onCleanup(@() local_cleanup_temp_root(temp_root)); %#ok<NASGU>

    data_file = fullfile(temp_root, 'synthetic_double_wedge_test.dat');
    figure_dir = fullfile(temp_root, 'figs');
    local_write_multiline_zone_file(data_file);

    cfg = config_case();
    cfg.io.baseflow_file = data_file;
    cfg.io.boundary_file = '';
    cfg.io.output_root = temp_root;
    cfg.io.figure_dir = figure_dir;
    cfg.io.mat_dir = fullfile(temp_root, 'mat');
    cfg.io.log_dir = fullfile(temp_root, 'logs');
    cfg.reader.stride_x = 1;
    cfg.reader.stride_y = 1;
    cfg.reader.remove_duplicate_terminal_lines = false;

    base = read_phenglei_baseflow(cfg);

    assert(~base.metadata.using_headerless_fallback, ...
        'The multiline ZONE header should be parsed without the fallback path.');
    assert(isequal(base.metadata.original_dims, [2, 2]), ...
        'The multiline ZONE header dimensions were not parsed correctly.');
    assert(base.metadata.num_vars_read == 12, ...
        'The multiline header test should preserve the 12-column PHengLEI layout.');
    assert(base.metadata.gamma_column_present, ...
        'The multiline header test should preserve the twelfth gama column.');
    assert(base.Nx == 2 && base.Ny == 2, ...
        'Stride-1 read should preserve the raw 2x2 dimensions.');
    assert(abs(base.gama(2, 2) - 1.40) < 1.0e-12, ...
        'The twelfth PHengLEI column should be mapped for headered files too.');
    assert(exist(fullfile(figure_dir, cfg.plot.boundary_audit_name), 'file') == 2, ...
        'Boundary-audit figure was not written for the parsed test case.');

    fprintf('[test_read_phenglei_multiline_zone_header] PASS\n');
end

function local_write_multiline_zone_file(path_name)
%LOCAL_WRITE_MULTILINE_ZONE_FILE Create a tiny Tecplot POINT sample.

    lines = { ...
        'TITLE     = "Flow Fields of PHengLEI"'; ...
        'VARIABLES = "x"'; ...
        '"y"'; ...
        '"z"'; ...
        '"density"'; ...
        '"u"'; ...
        '"v"'; ...
        '"w"'; ...
        '"pressure"'; ...
        '"temperature"'; ...
        '"mach"'; ...
        '"cp"'; ...
        '"gama"'; ...
        'ZONE T="Zone0 BLK"'; ...
        ' STRANDID=0, SOLUTIONTIME=0'; ...
        ' I=2, J=2, K=1, ZONETYPE=Ordered'; ...
        ' DATAPACKING=POINT'; ...
        ' DT=(SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE SINGLE)'; ...
        ' -1.0 0.0 0.0 1.0 10.0 0.0 0.0 100.0 300.0 5.0 0.1 1.40'; ...
        ' 1.0 0.0 0.0 1.1 11.0 0.1 0.0 101.0 301.0 5.1 0.2 1.40'; ...
        ' -1.0 1.0 0.0 1.2 12.0 0.2 0.0 102.0 302.0 5.2 0.3 1.40'; ...
        ' 1.0 1.0 0.0 1.3 13.0 0.3 0.0 103.0 303.0 5.3 0.4 1.40' ...
        };

    fid = fopen(path_name, 'w');
    if fid == -1
        error('test_read_phenglei_multiline_zone_header:IO', ...
            'Unable to create temporary data file: %s', path_name);
    end
    cleanup_obj = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fprintf(fid, '%s\n', lines{:});
end

function local_cleanup_temp_root(temp_root)
%LOCAL_CLEANUP_TEMP_ROOT Remove the temporary test workspace.

    if exist(temp_root, 'dir') == 7
        rmdir(temp_root, 's');
    end
end
