function test_paperA_beta_terms_v6()
%TEST_PAPERA_BETA_TERMS_V6 Validate explicit beta-dependent primitive-five terms.

    project_root = fileparts(fileparts(mfilename('fullpath')));
    addpath(project_root);
    addpath(fullfile(project_root, 'src', 'core'));

    N = 6;
    Dx = spdiags([-ones(N, 1), ones(N, 1)], [-1, 1], N, N);
    Dy = spdiags([-2 * ones(N, 1), 2 * ones(N, 1)], [-1, 1], N, N);
    I = speye(N);

    mu0 = 2.0 * ones(N, 1);
    mu_x = zeros(N, 1);
    mu_y = zeros(N, 1);
    p0 = 3.0 * ones(N, 1);
    rho0 = 4.0 * ones(N, 1);
    div0 = zeros(N, 1);
    fac_vis = 0.25;
    fac_heat = 0.5;

    [beta_zero_terms, beta_zero_audit] = build_paperA_beta_terms_v6(Dx, Dy, I, ...
        'Beta', 0.0, ...
        'Mu0', mu0, ...
        'MuX', mu_x, ...
        'MuY', mu_y, ...
        'P0', p0, ...
        'Rho0', rho0, ...
        'Div0', div0, ...
        'FacVis', fac_vis, ...
        'FacHeat', fac_heat);
    zero_names = {'Luu', 'Lvv', 'Luw', 'Lvw', 'Lwu', 'Lwv', 'Lww', 'LwP', 'LTw', 'LTT', 'LPw'};
    for k = 1:numel(zero_names)
        assert(nnz(beta_zero_terms.(zero_names{k})) == 0, ...
            'beta=0 should zero out %s.', zero_names{k});
    end
    assert(beta_zero_audit.zero_beta_all_zero, ...
        'The beta audit should mark beta=0 as identically zero.');

    beta = 1.7;
    [beta_terms, beta_audit] = build_paperA_beta_terms_v6(Dx, Dy, I, ...
        'Beta', beta, ...
        'Mu0', mu0, ...
        'MuX', mu_x, ...
        'MuY', mu_y, ...
        'P0', p0, ...
        'Rho0', rho0, ...
        'Div0', div0, ...
        'FacVis', fac_vis, ...
        'FacHeat', fac_heat);

    assert(norm(beta_terms.LwP - (-1i * beta * I), 'fro') < 1.0e-12, ...
        'LwP should match the expected -i*beta identity coupling.');
    assert(norm(beta_terms.LPw - (-1i * beta * spdiags(rho0, 0, N, N)), 'fro') < 1.0e-12, ...
        'LPw should match the expected -i*beta*rho0 coupling.');
    assert(norm(beta_terms.LTw - (-1i * beta * spdiags(p0, 0, N, N)), 'fro') < 1.0e-12, ...
        'LTw should reduce to -i*beta*p0 on zero-divergence uniform baseflow.');
    assert(norm(beta_terms.Luu - (-fac_vis * spdiags(mu0 * beta^2, 0, N, N)), 'fro') < 1.0e-12, ...
        'Luu beta^2 damping should match the expected diagonal term.');
    assert(norm(beta_terms.Lvv - (-fac_vis * spdiags(mu0 * beta^2, 0, N, N)), 'fro') < 1.0e-12, ...
        'Lvv beta^2 damping should match the expected diagonal term.');
    assert(norm(beta_terms.Lww - (-fac_vis * spdiags((4.0 / 3.0) * mu0 * beta^2, 0, N, N)), 'fro') < 1.0e-12, ...
        'Lww beta^2 damping should match the expected 4/3 diagonal term.');
    assert(norm(beta_terms.LTT - (-fac_heat * spdiags(mu0 * beta^2, 0, N, N)), 'fro') < 1.0e-12, ...
        'LTT beta^2 thermal damping should match the expected diagonal term.');
    assert(beta_audit.has_spanwise_terms, ...
        'The audit should mark nonzero beta as having spanwise terms.');

    fprintf('[test_paperA_beta_terms_v6] PASS\n');
end
