function test_write_paperA_reference_figures_no_plot_candidate()
%TEST_WRITE_PAPERA_REFERENCE_FIGURES_NO_PLOT_CANDIDATE
% Ensure the figure writer emits only the spectrum when no physical plot candidate exists.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    fig_dir = fullfile(project_root, 'outputs', 'mat', 'test_write_paperA_reference_figures_no_plot_candidate');
    if exist(fig_dir, 'dir') == 7
        rmdir(fig_dir, 's');
    end
    mkdir(fig_dir);

    Ny = 10;
    Nx = 12;
    [X, Y] = meshgrid(linspace(0.0, 1.0, Nx), linspace(0.0, 0.4, Ny));
    layout = get_state_layout_info('primitive5_u_v_w_T_p');

    ranking = struct();
    ranking.EigVals = [0.01 + 0.02i; -0.01 + 0.01i];
    ranking.EigVecs = zeros(layout.nvar * Ny * Nx, 2);
    ranking.residuals = [1.0e-8; 2.0e-8];
    ranking.selected_for_plots = false(2, 1);
    ranking.order = (1:2).';
    ranking.freq_info = struct('freq_nd_signed', [0.02; 0.01]);
    ranking.metrics = struct( ...
        'u_peak_in_bubble', false(2, 1), ...
        'bubble_core_overlap', zeros(2, 1), ...
        'bubble_support_overlap', zeros(2, 1), ...
        'near_wall_energy_frac', zeros(2, 1), ...
        'shock_energy_frac', zeros(2, 1), ...
        'shock_core_energy_frac', zeros(2, 1), ...
        'u_peak_in_shock_core', false(2, 1), ...
        'outlet_energy_frac', zeros(2, 1), ...
        'outlet_wall_energy_frac', zeros(2, 1), ...
        'u_peak_in_outlet_wall', false(2, 1), ...
        'free_stream_energy_frac', zeros(2, 1), ...
        'checker_ratio', zeros(2, 1), ...
        'physical_candidate_score', zeros(2, 1), ...
        'family_priority', zeros(2, 1), ...
        'component_support', struct('w', struct( ...
            'bubble_support_overlap', zeros(2, 1), ...
            'bubble_core_overlap', zeros(2, 1), ...
            'shock_core_overlap', zeros(2, 1), ...
            'peak_in_bubble_support', false(2, 1), ...
            'peak_in_shock_core', false(2, 1))));

    data = struct();
    data.Nx = Nx;
    data.Ny = Ny;
    data.X = X;
    data.Y = Y;
    data.U = ones(Ny, Nx);
    data.V = zeros(Ny, Nx);
    data.RHO = ones(Ny, Nx);
    data.GeometryAudit = struct();
    data.BaseflowMasks = struct( ...
        'bubble_mask', false(Ny, Nx), ...
        'bubble_core_mask', false(Ny, Nx));

    Config = struct();
    Config.Cv_nd = 0.12;
    Config.state_layout = layout.name;
    Config.target_benchmark = 'Sidharth2018';
    Config.plot_contract = 'paperA_reference_mainset_v1';
    Config.secondary_plot_contract = 'sidharth2018_reproduction_v1';
    Config.plot_debug_mode_diagnosis = false;

    PhaseAudit_s = repmat(struct('type', 'none', 'row', NaN, 'col', NaN, 'x', NaN, 'y', NaN), 2, 1);
    FigureAudit = write_paperA_reference_figures(fig_dir, ranking, data, Config, ones(2, 1), PhaseAudit_s);

    assert(strcmp(FigureAudit.status, 'no_physical_plot_candidate'), ...
        'The figure writer should preserve the explicit no-plot status.');
    assert(exist(fullfile(fig_dir, 'Fig13_EigenvalueSpectrum.png'), 'file') == 2, ...
        'The spectrum figure should still be emitted for no-plot cases.');
    assert(exist(fullfile(fig_dir, 'Fig18_LeadingModeRawNormalized_uvpT.png'), 'file') ~= 2, ...
        'No-plot cases must not emit the full-field lead figure.');
    assert(exist(fullfile(fig_dir, 'Fig19_LeadingModeBubbleStreamlines_uvpT.png'), 'file') ~= 2, ...
        'No-plot cases must not emit the bubble-window lead figure.');
    assert(isempty(FigureAudit.sidharth_output_files), ...
        'No-plot cases must not emit Sidharth component figures.');

    fprintf('[test_write_paperA_reference_figures_no_plot_candidate] PASS\n');
end
