function test_run_user_test_reuse_case_provenance_v6()
%TEST_RUN_USER_TEST_REUSE_CASE_PROVENANCE_V6 Guard reuse-safe provenance metadata.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    case_name = 'test_run_user_test_reuse_case_provenance_v6';
    case_dir = fullfile(project_root, 'outputs', 'mat', case_name);
    if exist(case_dir, 'dir') == 7
        rmdir(case_dir, 's');
    end

    fresh_summary = run_user_test_baseflow_fullres_v6( ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'TopType', 'inlet', ...
        'WallModel', 'adiabatic', ...
        'RunPart4', false, ...
        'Part3Variant', 'current_v6', ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false, ...
        'CaseName', case_name);

    assert(exist(fullfile(case_dir, 'RunnerCaseMetadata.mat'), 'file') == 2, ...
        'Fresh configurable runs should save explicit runner provenance metadata.');
    assert(strcmp(fresh_summary.part3_variant_used, 'current_v6'), ...
        'Fresh run should record the active Part3 implementation.');

    reuse_summary = run_user_test_baseflow_fullres_v6( ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'TopType', 'inlet', ...
        'WallModel', 'adiabatic', ...
        'RunPart4', false, ...
        'Part3Variant', 'current_v6', ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false, ...
        'ReuseExistingCase', true, ...
        'CaseName', case_name);

    assert(reuse_summary.reuse_existing_case, ...
        'ReuseExistingCase=true should be reflected in the returned summary.');
    assert(isequal(reuse_summary.expected_dims, [270, 128]), ...
        'Reuse summary should report the saved case dimensions instead of the current call arguments.');
    assert(all(reuse_summary.stride == [30, 20]), ...
        'Reuse summary should report the saved downsampling stride.');
    assert(strcmp(reuse_summary.part3_variant_used, 'current_v6'), ...
        'Reuse summary should keep the saved Part3 variant.');

    mismatch_id = '';
    try
        run_user_test_baseflow_fullres_v6( ...
            'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
            'ExpectedDims', [270, 128], ...
            'StrideX', 30, ...
            'StrideY', 20, ...
            'TopType', 'inlet', ...
            'RunPart4', false, ...
            'Part3Variant', 'pre_pressure_fix_20260414', ...
            'UseSemiArtificialViscosity', false, ...
            'UseShockSourceRegularization', false, ...
            'UsePressureRowRegularization', false, ...
            'ReuseExistingCase', true, ...
            'CaseName', case_name);
    catch ME
        mismatch_id = ME.identifier;
    end

    assert(strcmp(mismatch_id, 'run_user_test_baseflow_fullres_v6:ReuseMismatch'), ...
        'ReuseExistingCase should reject parameter sets that do not match the saved case provenance.');

    benchmark_mismatch_id = '';
    try
        run_user_test_baseflow_fullres_v6( ...
            'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
            'ExpectedDims', [270, 128], ...
            'StrideX', 30, ...
            'StrideY', 20, ...
            'TopType', 'inlet', ...
            'BenchmarkProfile', 'manual_test_profile', ...
            'RunPart4', false, ...
            'Part3Variant', 'current_v6', ...
            'UseSemiArtificialViscosity', false, ...
            'UseShockSourceRegularization', false, ...
            'UsePressureRowRegularization', false, ...
            'ReuseExistingCase', true, ...
            'CaseName', case_name);
    catch ME
        benchmark_mismatch_id = ME.identifier;
    end

    assert(strcmp(benchmark_mismatch_id, 'run_user_test_baseflow_fullres_v6:ReuseMismatch'), ...
        'ReuseExistingCase should reject benchmark-profile mismatches too.');

    wall_mismatch_id = '';
    try
        run_user_test_baseflow_fullres_v6( ...
            'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
            'ExpectedDims', [270, 128], ...
            'StrideX', 30, ...
            'StrideY', 20, ...
            'TopType', 'inlet', ...
            'WallModel', 'isothermal', ...
            'RunPart4', false, ...
            'Part3Variant', 'current_v6', ...
            'UseSemiArtificialViscosity', false, ...
            'UseShockSourceRegularization', false, ...
            'UsePressureRowRegularization', false, ...
            'ReuseExistingCase', true, ...
            'CaseName', case_name);
    catch ME
        wall_mismatch_id = ME.identifier;
    end

    assert(strcmp(wall_mismatch_id, 'run_user_test_baseflow_fullres_v6:ReuseMismatch'), ...
        'ReuseExistingCase should reject wall-model mismatches too.');

    fprintf('[test_run_user_test_reuse_case_provenance_v6] PASS\n');
end
