function test_run_research_workflow_part3_only_v6()
%TEST_RUN_RESEARCH_WORKFLOW_PART3_ONLY_V6 Smoke-test the staged workflow runner.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    workflow_name = 'test_research_workflow_part3_only_v6';
    workflow_dir = fullfile(project_root, 'outputs', 'mat', workflow_name);
    if exist(workflow_dir, 'dir') == 7
        rmdir(workflow_dir, 's');
    end

    workflow = run_research_workflow_v6( ...
        'WorkflowName', workflow_name, ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'TopType', 'inlet', ...
        'AuditBetas', 0.0, ...
        'RunRegularizationCompare', false, ...
        'RunBetaScan', false, ...
        'RunRefinedPart4', false, ...
        'RunResolventScan', false, ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false, ...
        'NEigsAudit', 20);

    assert(numel(workflow.audit_cases) == 1, ...
        'The staged workflow should return one Part3 audit case for the requested beta set.');
    assert(strcmp(workflow.audit_cases(1).summary.stage_completed, 'Part3'), ...
        'The smoke workflow should stop the audit case after Part3.');
    assert(height(workflow.stage_records) == 1, ...
        'Only one stage record should be present when every later stage is disabled.');
    assert(exist(fullfile(workflow_dir, 'research_workflow_summary.mat'), 'file') == 2, ...
        'The staged workflow should save one summary MAT file.');
    assert(exist(fullfile(workflow_dir, 'research_workflow_summary.txt'), 'file') == 2, ...
        'The staged workflow should save one summary text file.');

    fprintf('[test_run_research_workflow_part3_only_v6] PASS\n');
end
