function test_run_sidharth2018_workflow_part3_only_v6()
%TEST_RUN_SIDHARTH2018_WORKFLOW_PART3_ONLY_V6 Smoke-test the Sidharth workflow preset.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    workflow_name = 'test_run_sidharth2018_workflow_part3_only_v6';
    workflow_dir = fullfile(project_root, 'outputs', 'mat', workflow_name);
    if exist(workflow_dir, 'dir') == 7
        rmdir(workflow_dir, 's');
    end

    workflow = run_sidharth2018_workflow_v6( ...
        'WorkflowName', workflow_name, ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'AuditBetas', 0.0, ...
        'RunRegularizationCompare', false, ...
        'RunBetaScan', false, ...
        'RunRefinedPart4', false, ...
        'RunResolventScan', false, ...
        'NEigsAudit', 20);

    assert(strcmp(workflow.benchmark_profile, 'sidharth2018_code_correction_v1'), ...
        'The Sidharth preset should lock the benchmark profile.');
    assert(numel(workflow.audit_cases) == 1, ...
        'The smoke configuration should run exactly one audit case.');
    assert(strcmp(workflow.audit_cases(1).summary.stage_completed, 'Part3'), ...
        'The smoke configuration should stop after Part3.');
    assert(strcmp(workflow.audit_cases(1).summary.benchmark_profile, 'sidharth2018_code_correction_v1'), ...
        'Audit-case summaries should preserve the Sidharth benchmark profile.');
    assert(exist(fullfile(workflow_dir, 'research_workflow_summary.mat'), 'file') == 2, ...
        'The Sidharth preset should still save the workflow summary MAT file.');

    fprintf('[test_run_sidharth2018_workflow_part3_only_v6] PASS\n');
end
