function test_run_sigma_shift_scan_part3_only_v6()
%TEST_RUN_SIGMA_SHIFT_SCAN_PART3_ONLY_V6 Smoke-test the configurable sigma-shift scan without Part4.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    scan_name = 'test_sigma_shift_scan_part3_only_v6';
    scan_dir = fullfile(project_root, 'outputs', 'mat', scan_name);
    if exist(scan_dir, 'dir') == 7
        rmdir(scan_dir, 's');
    end

    shifts = [0.01 + 0.01i, 0.02 + 0.015i];
    scan = run_sigma_shift_scan_v6( ...
        'ScanCaseName', scan_name, ...
        'SigmaShifts', shifts, ...
        'LockSigmaTripletToShift', false, ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'RunPart4', false, ...
        'Part3Variant', 'current_v6', ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false);

    assert(numel(scan.cases) == numel(shifts), ...
        'Sigma-shift scan should return one case per requested shift.');
    assert(height(scan.summary_table) == numel(shifts), ...
        'Sigma-shift scan summary table should have one row per requested shift.');
    stages = arrayfun(@(s) s.summary.stage_completed, scan.cases, 'UniformOutput', false);
    assert(all(strcmp(stages, 'Part3')), ...
        'Part3-only sigma-shift scan should stop every case before Part4.');
    part1_case1 = load(fullfile(scan.cases(1).case_dir, 'Part1_Results.mat'), 'Config');
    expected_triplet = [0.00 + 0.005i, 0.00 + 0.010i, 0.00 + 0.020i, 0.02 + 0.020i, 0.05 + 0.020i];
    assert(isequal(part1_case1.Config.sigma_triplet, expected_triplet), ...
        ['Empty SigmaTriplet should keep the default Part1 shift family ' ...
         'when LockSigmaTripletToShift=false.']);
    assert(part1_case1.Config.sigma == shifts(1), ...
        'Each scan case should still keep its own primary SigmaShift.');
    assert(exist(fullfile(scan_dir, 'sigma_shift_scan_summary.mat'), 'file') == 2, ...
        'Sigma-shift scan should save one summary MAT file.');

    fprintf('[test_run_sigma_shift_scan_part3_only_v6] PASS\n');
end
