function test_run_user_test_baseflow_part3_only_v6()
%TEST_RUN_USER_TEST_BASEFLOW_PART3_ONLY_V6 Smoke-test the configurable runner without Part4.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    case_name = 'test_run_user_test_part3_only_v6';
    case_dir = fullfile(project_root, 'outputs', 'mat', case_name);
    if exist(case_dir, 'dir') == 7
        rmdir(case_dir, 's');
    end

    summary = run_user_test_baseflow_fullres_v6( ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'TopType', 'inlet', ...
        'RunPart4', false, ...
        'Part3Variant', 'current_v6', ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false, ...
        'CaseName', case_name);

    assert(strcmp(summary.stage_completed, 'Part3'), ...
        'RunPart4=false should stop the configurable runner after Part3.');
    assert(strcmp(summary.part3_variant_used, 'current_v6'), ...
        'The runner should record the actual Part3 implementation used.');
    assert(~summary.has_part4, ...
        'Part3-only runs should report has_part4=false.');
    assert(~summary.use_shock_source_regularization, ...
        'Config overrides should disable shock_source_regularization in the saved summary.');
    assert(~summary.pressure_row_regularization.enabled, ...
        'Config overrides should disable pressure-row regularization in the saved summary.');
    assert(exist(fullfile(case_dir, 'Part3_Results.mat'), 'file') == 2, ...
        'Part3-only runner should still save Part3_Results.mat.');

    fprintf('[test_run_user_test_baseflow_part3_only_v6] PASS\n');
end
