function test_run_research_workflow_refined_part4_no_adjoint_v6()
%TEST_RUN_RESEARCH_WORKFLOW_REFINED_PART4_NO_ADJOINT_V6
% Verify the staged workflow can run a tiny refined Part4 case without adjoint diagnostics.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    workflow_name = 'test_research_workflow_refined_part4_no_adjoint_v6';
    workflow_dir = fullfile(project_root, 'outputs', 'mat', workflow_name);
    if exist(workflow_dir, 'dir') == 7
        rmdir(workflow_dir, 's');
    end

    workflow = run_research_workflow_v6( ...
        'WorkflowName', workflow_name, ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'TopType', 'inlet', ...
        'AuditBetas', 0.0, ...
        'RunRegularizationCompare', false, ...
        'RunBetaScan', false, ...
        'RunRefinedPart4', true, ...
        'EnableRefinedAdjointLeadDiagnostics', false, ...
        'RunResolventScan', false, ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false, ...
        'NEigsAudit', 6, ...
        'NEigsRefined', 6, ...
        'SigmaShift', 0.01 + 0.01i, ...
        'SigmaTriplet', 0.01 + 0.01i, ...
        'ForceLowMemoryDescriptor', true);

    assert(strcmp(workflow.refined_case.stage_completed, 'Part4'), ...
        'The refined workflow smoke case should complete through Part4.');
    assert(~workflow.flags.enable_refined_adjoint_lead_diagnostics, ...
        'The workflow flags should record adjoint diagnostics as disabled.');

    part1 = load(fullfile(workflow.refined_case.case_dir, 'Part1_Results.mat'), 'Config');
    assert(~part1.Config.analysis.compute_adjoint_lead, ...
        'The refined workflow case should keep Config.analysis.compute_adjoint_lead disabled.');

    part4 = load(fullfile(workflow.refined_case.case_dir, 'Part4_Results.mat'), 'AdjointLeadAudit');
    assert(isfield(part4, 'AdjointLeadAudit') && isstruct(part4.AdjointLeadAudit), ...
        'The refined workflow case should still save an AdjointLeadAudit struct.');
    assert(isfield(part4.AdjointLeadAudit, 'enabled') && ~part4.AdjointLeadAudit.enabled, ...
        'AdjointLeadAudit.enabled should stay false when diagnostics are disabled.');

    fprintf('[test_run_research_workflow_refined_part4_no_adjoint_v6] PASS\n');
end
