function test_run_beta_scan_part3_only_v6()
%TEST_RUN_BETA_SCAN_PART3_ONLY_V6 Smoke-test the reusable beta scan without Part4.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    scan_name = 'test_beta_scan_part3_only_v6';
    scan_dir = fullfile(project_root, 'outputs', 'mat', scan_name);
    if exist(scan_dir, 'dir') == 7
        rmdir(scan_dir, 's');
    end

    betas = [0.0, 0.20];
    scan = run_beta_scan_v6( ...
        'ScanCaseName', scan_name, ...
        'Betas', betas, ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'WallModel', 'isothermal', ...
        'WallTemperature', 298.0, ...
        'RunPart4', false, ...
        'Part3Variant', 'current_v6', ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false);

    assert(numel(scan.cases) == numel(betas), ...
        'Beta scan should return one case per requested beta.');
    assert(height(scan.summary_table) == numel(betas), ...
        'Beta scan summary table should have one row per requested beta.');
    stages = arrayfun(@(s) s.summary.stage_completed, scan.cases, 'UniformOutput', false);
    assert(all(strcmp(stages, 'Part3')), ...
        'Part3-only beta scan should stop every case before Part4.');
    assert(strcmp(scan.wall_model, 'isothermal'), ...
        'Beta scan summary should record the requested wall model.');
    assert(strcmp(scan.cases(1).summary.wall_model, 'isothermal'), ...
        'Beta scan should propagate wall-model settings into each case.');
    assert(all(abs(scan.summary_table.beta - betas(:)) <= 1.0e-12), ...
        'Saved beta values should match the requested scan values.');
    assert(exist(fullfile(scan_dir, 'beta_scan_summary.mat'), 'file') == 2, ...
        'Beta scan should save one summary MAT file.');

    fprintf('[test_run_beta_scan_part3_only_v6] PASS\n');
end
