function test_run_resolvent_gain_scan_v6()
%TEST_RUN_RESOLVENT_GAIN_SCAN_V6 Smoke-test the Part3-based resolvent wrapper.

    paths = setup_double_wedge_paths('IncludeTests', true);
    project_root = paths.project_root;

    case_name = 'test_run_resolvent_gain_scan_v6';
    case_dir = fullfile(project_root, 'outputs', 'mat', case_name);
    if exist(case_dir, 'dir') == 7
        rmdir(case_dir, 's');
    end

    result = run_resolvent_gain_scan_v6( ...
        'CaseName', case_name, ...
        'BaseflowFile', fullfile(project_root, 'double_wedge_baseflow.dat'), ...
        'ExpectedDims', [270, 128], ...
        'StrideX', 30, ...
        'StrideY', 20, ...
        'SigmaList', 1i * [0.01, 0.02], ...
        'WallModel', 'isothermal', ...
        'WallTemperature', 298.0, ...
        'Part3Variant', 'current_v6', ...
        'UseSemiArtificialViscosity', false, ...
        'UseShockSourceRegularization', false, ...
        'UsePressureRowRegularization', false);

    assert(strcmp(result.part3_summary.stage_completed, 'Part3'), ...
        'The resolvent wrapper should build on a Part3-only runner summary.');
    assert(strcmp(result.wall_model, 'isothermal'), ...
        'The resolvent wrapper should report the requested wall model.');
    assert(height(result.summary_table) == 2, ...
        'The resolvent wrapper should return one row per requested sigma.');
    assert(exist(fullfile(case_dir, 'resolvent_gain_scan.mat'), 'file') == 2, ...
        'The resolvent wrapper should save one summary MAT file.');

    fprintf('[test_run_resolvent_gain_scan_v6] PASS\n');
end
