function label = localize_output_label(key)
%LOCALIZE_OUTPUT_LABEL Map user-facing output labels to Chinese-friendly text.

    key_text = char(string(key));
    key_norm = lower(strtrim(key_text));

    persistent exact_map token_map
    if isempty(exact_map)
        exact_keys = { ...
            'user test baseflow full-resolution v6 run', ...
            'baseflow import audit v6', ...
            'beta scan v6', ...
            'sigma-shift scan v6', ...
            'double-wedge research workflow v6', ...
            'resolvent gain scan v6', ...
            'beta=4 part4-only local shift scan', ...
            'run_stage', 'baseflow_file', 'case_dir', 'figure_directory', ...
            'reuse_existing_case', 'expected_dims', 'working_dims', 'stride', ...
            'top_type', 'benchmark_profile', 'target_benchmark', ...
            'primary_plot_contract', 'secondary_plot_contract', 'state_layout', ...
            'operator_model', 'part3_variant_requested', 'part3_variant_used', ...
            'part3_variant', 'ma_inf', 're_inf', 't_inf', 'gamma', 'pr', ...
            'wall_model', 't_wall', 't_wall_nd', 'n_eigs', 'beta', 'use_sponge', ...
            'use_semi_artificial_viscosity', 'use_shock_source_regularization', ...
            'pressure_row_regularization_enabled', 'sigma_shift', 'sigma_triplet', ...
            'base_eos_relative_error', 'base_wall_temperature_relative_mismatch', ...
            'base_wall_model', 'base_wall_temperature_check_applied', ...
            'base_wall_temperature_target', 'base_wall_temperature_target_nd', ...
            'continuity_residual_max', 'bubble_exists', ...
            'leading_mode_available', 'leading_mode_position', ...
            'leading_mode_original_index', 'leading_mode_resolution_status', ...
            'leading_mode_resolution_source', 'leading_sigma', 'leading_freq_nd', ...
            'leading_freq_signed', 'leading_residual', 'leading_residual_active', ...
            'leading_residual_algebraic', 'leading_residual_scaled', ...
            'leading_bubble_overlap', 'leading_near_wall_energy_frac', ...
            'leading_free_stream_energy_frac', 'leading_outlet_energy_frac', ...
            'leading_outlet_wall_energy_frac', 'leading_shock_energy_frac', ...
            'leading_checker_ratio', 'leading_mode_family', ...
            'leading_physical_candidate_score', 'leading_bubble_shock_phase_deg', ...
            'leading_bubble_shock_sync', 'leading_reference_component', ...
            'leading_selected_for_plots', 'leading_selected_for_publication', ...
            'selection_status', 'publication_allowed', ...
            'mode_validity_primary_reason', 'adjoint_lead_enabled', ...
            'adjoint_lead_reason', 'wavemaker_bubble_frac', ...
            'wavemaker_shock_frac', 'matrix_row_ratio_before', ...
            'matrix_row_ratio_after', 'matrix_zero_rows', 'matrix_zero_cols', ...
            'operator_row_ratio_before', 'operator_shock_to_nonshock_row_ratio', ...
            'shock_mask_coverage', 'derivative_clip_total', ...
            'derivative_zero_total', 'sav_active_rows', 'sav_active_points', ...
            'beta_terms_active', 'pressure_row_total_clipped', ...
            'pressure_row_total_zeroed', ...
            'pressure_closure_rho_from_p_density_residual_max', ...
            'pressure_closure_pressure_scale_density_residual_max', ...
            'pressure_closure_linearized_eos_balance_residual_max', ...
            'literature benchmark audit', 'baseflow reference table', ...
            'mode reference table', 'eigen reference table', ...
            'figure criteria table', 'plot provenance audit', ...
            'plot contract audit', 'figure audit', 'top modes', ...
            'operator ablation table', 'post-bc ablation audit', ...
            'lead component audit', 'scan_case', 'run_part4', 'stage', ...
            'bubble', 'shock', 'checker', 'family', 'corr_to_prev', ...
            'shift', 'row_ratio_before', 'shock_coverage', 'pressure_clip', ...
            'source_case', 'gain', 'sigma_min', 'near_wall', 'free_stream', ...
            'outlet_wall', 'solver', 'workflow_name', 'workflow_root_dir', ...
            'force_low_memory_descriptor', 'audit_betas', 'beta_scan_betas', ...
            'regularization_compare_beta', 'refined_beta', 'resolvent_beta', ...
            'resolvent_sigma_list', 'stage records', 'stage_type', 'label', ...
            'stage_completed', 'raw_dims', 'num_vars_read', 'standard_num_vars', ...
            'gamma_column_present', 'num_optional_standard_vars', 'num_extra_vars', ...
            'num_vars_inferred', 'eos_relative_error', ...
            'eos_relative_error_stats', 'wall_temperature_relative_mismatch', ...
            'required_eos_relation', 'boundary_contract_match', ...
            'reference_scales_defined', 'profile_target_match', ...
            'structural_only', 'physics_reproduction_ready', ...
            'pressure stats', 'rho stats', ...
            'temperature stats', 'mach stats', 'w stats', 'top-row means', ...
            'item', 'value', 'component', 'bubble_support', 'bubble_core', 'shock_core', ...
            'peak_in_bubble', 'peak_in_shock', 'plot_mode_position', ...
            'reference_component', 'normalization', 'normalization_scale', ...
            'phase_anchor_type', 'phase_anchor_x', 'phase_anchor_y', ...
            'has_plot_lead', 'plot_status', 'figure_status', ...
            'sidharth_component_contract', 'sidharth_gallery_component', ...
            'lead_plot_index', 'status', 'num_gallery_pages', ...
            'sidharth_gallery_pages', 'figure', 'what_to_compare', ...
            'pass_signal', 'reject_signal', 'num_boundary_rows', ...
            'num_overwritten_rows', 'pressure_row_outside_shock_points'};
        exact_values = { ...
            '用户测试基本流全分辨率 v6 运行摘要', ...
            '基本流导入审计 v6', ...
            'beta 扫描 v6', ...
            'sigma-shift 扫描 v6', ...
            '双楔研究工作流 v6', ...
            'Resolvent 增益扫描 v6', ...
            'beta=4 仅 Part4 局部 shift 扫描', ...
            '运行阶段', '基本流文件', '算例目录', '图像目录', ...
            '复用已有算例', '期望网格', '工作网格', '采样步长', ...
            '顶边类型', '基准配置', '目标文献基准', ...
            '主绘图合同', '次绘图合同', '状态布局', ...
            '算子模型', '请求的 Part3 变体', '实际 Part3 变体', ...
            'Part3 变体', 'Ma_inf', 'Re_inf', 'T_inf', 'gamma', 'Pr', ...
            '壁面模型', 'T_wall', 'T_wall_nd', '特征值数', 'beta', '海绵区', ...
            '半人工黏性', '激波源项正则化', ...
            '压力行正则化', 'sigma_shift', 'sigma_triplet', ...
            '基本流 EOS 相对误差', '壁面温度相对失配', ...
            '基本流壁面模型', '是否检查壁温', ...
            '壁面温度目标', '壁面温度目标（无量纲）', ...
            '连续方程残差最大值', '分离泡是否存在', ...
            '主导模态是否可用', '主导模态位置', ...
            '主导模态原始索引', '主导模态解析状态', ...
            '主导模态解析来源', '主导 sigma', '主导无量纲频率', ...
            '主导带符号频率', '主导残差', '主导活动残差', ...
            '主导代数残差', '主导缩放残差', ...
            '主导分离泡重叠', '主导近壁能量占比', ...
            '主导自由流能量占比', '主导出口能量占比', ...
            '主导出口壁面能量占比', '主导激波能量占比', ...
            '主导棋盘比', '主导模态家族', ...
            '主导物理候选得分', '主导分离泡-激波相位差', ...
            '主导分离泡-激波同步性', '主导参考分量', ...
            '主导用于绘图', '主导用于发表', ...
            '筛选状态', '允许发表', ...
            '模态有效性主因', '伴随主导诊断', ...
            '伴随主导原因', '波源器分离泡占比', ...
            '波源器激波占比', '矩阵行范数比（BC前）', ...
            '矩阵行范数比（BC后）', '矩阵零行数', '矩阵零列数', ...
            '算子行范数比（BC前）', '激波/非激波行范数比', ...
            '激波掩码覆盖率', '导数裁剪总数', ...
            '导数置零总数', 'SAV 激活行数', 'SAV 激活点数', ...
            'beta 项已激活', '压力行裁剪总数', ...
            '压力行置零总数', ...
            '压力闭合 rho_from_p 密度残差最大值', ...
            '压力闭合 pressure_scale 密度残差最大值', ...
            '压力闭合线性化 EOS 平衡残差最大值', ...
            '文献基准审计', '基本流参考表', ...
            '模态参考表', '特征值参考表', ...
            '图像判据表', '绘图溯源审计', ...
            '绘图合同审计', '图像审计', '候选模态概览', ...
            '算子消融表', '边界覆盖后消融审计', ...
            '主导模态分量审计', '扫描算例', '运行 Part4', '阶段', ...
            '分离泡', '激波', '棋盘比', '模态家族', '与前一支相关性', ...
            'shift', '行范数比（BC前）', '激波覆盖率', '压力裁剪', ...
            '源算例', '增益', '最小奇异值', '近壁', '自由流', ...
            '出口壁面', '求解器', '工作流名称', '工作流根目录', ...
            '强制低内存描述符', '审计 beta 列表', 'beta 扫描列表', ...
            '正则化对比 beta', '精细 beta', 'Resolvent beta', ...
            'Resolvent sigma 列表', '阶段记录', '阶段类型', '标签', ...
            '完成阶段', '原始网格', '读取变量数', '标准变量数', ...
            'gamma 列存在', '可选标准变量数', '额外变量数', ...
            '推断变量数', 'EOS 相对误差', ...
            'EOS 相对误差统计', '壁面温度相对失配', ...
            '要求的 EOS 关系', '边界合同匹配', ...
            '参考尺度已定义', '配置与目标匹配', ...
            '仅结构算例', '物理复现实验就绪', ...
            '压力统计', 'rho 统计', ...
            '温度统计', 'Mach 统计', 'w 统计', '顶行均值', ...
            '项目', '数值', '分量', '分离泡支撑', '分离泡核心', '激波核心', ...
            '峰值在分离泡', '峰值在激波', '绘图模态位置', ...
            '参考分量', '归一化', '归一化尺度', ...
            '相位锚点类型', '相位锚点 x', '相位锚点 y', ...
            '存在绘图主模态', '绘图状态', '图像状态', ...
            'Sidharth 分量合同', 'Sidharth 图库分量', ...
            '绘图主索引', '状态', '图库页数', ...
            'Sidharth 图库页数', '图像', '比较内容', ...
            '通过信号', '拒绝信号', '边界行数', ...
            '覆盖改写行数', '激波外压力行点数'};

        exact_map = containers.Map(lower(exact_keys), exact_values);

        token_keys = {'bubble', 'shock', 'near', 'wall', 'free', 'stream', 'outlet', ...
            'mode', 'figure', 'plot', 'component', 'reference', 'energy', 'frac', ...
            'residual', 'stage', 'scan', 'summary', 'audit', 'workflow', 'baseflow', ...
            'import', 'pressure', 'row', 'regularization', 'gain', 'case', 'dir', ...
            'family', 'candidate', 'score', 'phase', 'status', 'source', 'selection', ...
            'publication', 'leading', 'top', 'boundary', 'mask', 'coverage', 'matrix', ...
            'operator', 'derivative', 'total', 'active', 'points', 'rows', 'cols', ...
            'normalization', 'contract', 'gallery', 'window'};
        token_values = {'分离泡', '激波', '近', '壁面', '自由', '流', '出口', ...
            '模态', '图像', '绘图', '分量', '参考', '能量', '占比', ...
            '残差', '阶段', '扫描', '摘要', '审计', '工作流', '基本流', ...
            '导入', '压力', '行', '正则化', '增益', '算例', '目录', ...
            '家族', '候选', '得分', '相位', '状态', '来源', '筛选', ...
            '发表', '主导', '顶边', '边界', '掩码', '覆盖率', '矩阵', ...
            '算子', '导数', '总数', '激活', '点数', '行数', '列数', ...
            '归一化', '合同', '图库', '窗口'};
        token_map = containers.Map(token_keys, token_values);
    end

    if isKey(exact_map, key_norm)
        label = exact_map(key_norm);
        return;
    end

    parts = regexp(key_text, '[_\-\s]+', 'split');
    if isempty(parts)
        label = key_text;
        return;
    end

    pieces = cell(size(parts));
    changed = false;
    for k = 1:numel(parts)
        token = lower(strtrim(parts{k}));
        if isempty(token)
            pieces{k} = '';
        elseif isKey(token_map, token)
            pieces{k} = token_map(token);
            changed = true;
        else
            pieces{k} = parts{k};
        end
    end

    if changed
        label = strjoin(pieces, '');
    else
        label = key_text;
    end
end
