function ranking = rank_paperA_modes(EigVals, EigVecs, residuals, residuals_active, residuals_algebraic, ...
        residuals_scaled, data, Config, masks)
%RANK_PAPERA_MODES Rank modes by Paper-A physical support rather than publication gates.

    Ny = data.Ny;
    Nx = data.Nx;
    num_modes = numel(EigVals);
    freq_info = interpret_sigma_eigenvalues(EigVals);

    mode_metrics = compute_mode_filter_metrics(EigVecs, Ny, Nx, data.RHO, Config.Cv_nd, ...
        'StateLayout', Config.state_layout, ...
        'NearWallFraction', Config.mode_filter.near_wall_fraction, ...
        'NearWallMask', masks.near_wall, ...
        'BubbleMask', masks.bubble_core, ...
        'BubbleSupportMask', masks.bubble_support, ...
        'FreeStreamMask', masks.free_stream, ...
        'SpongeSigma', data.sigma_sp, ...
        'ShockMask', masks.shock, ...
        'ShockCoreMask', masks.shock_core, ...
        'OutletMask', masks.outlet, ...
        'OutletWallMask', masks.outlet_wall, ...
        'CornerMask', masks.corner, ...
        'BadPointMask', masks.bad_point);

    ModeDiag = struct([]);
    farfield_ratio = zeros(num_modes, 1);
    highfreq_ratio = zeros(num_modes, 1);
    legacy_rejection_tags = cell(num_modes, 1);
    for k = 1:num_modes
        diag_k = compute_mode_diagnostics(EigVecs(:, k), Ny, Nx, ...
            'BoundaryMasks', data.BoundaryMasks, ...
            'X', data.X, 'Y', data.Y, 'U', data.U, ...
            'StateLayout', Config.state_layout);
        if k == 1
            ModeDiag = repmat(diag_k, num_modes, 1); %#ok<AGROW>
        end
        ModeDiag(k) = diag_k; %#ok<AGROW>
        farfield_ratio(k) = diag_k.farfield_energy_ratio;
        highfreq_ratio(k) = diag_k.highfreq_uv;
        legacy_rejection_tags{k} = evaluate_mode_validity_tags(diag_k, struct());
    end

    structural_only = false;
    if isfield(data, 'BaseflowPhysicsAudit') && isstruct(data.BaseflowPhysicsAudit) && ...
            isfield(data.BaseflowPhysicsAudit, 'structural_only_warning')
        structural_only = logical(data.BaseflowPhysicsAudit.structural_only_warning);
    end

    checker_threshold_used = Config.mode_filter.checker_threshold;
    bubble_threshold = local_get_mode_filter(Config, 'bubble_fraction_threshold', 0.05);
    shock_threshold = local_get_mode_filter(Config, 'shock_fraction_threshold', 0.35);
    shock_core_threshold = local_get_mode_filter(Config, 'shock_core_fraction_threshold', 0.15);
    free_stream_threshold = local_get_mode_filter(Config, 'free_stream_fraction_threshold', 0.20);
    outlet_threshold = local_get_mode_filter(Config, 'outlet_fraction_threshold', 0.35);
    outlet_wall_threshold = local_get_mode_filter(Config, 'outlet_wall_fraction_threshold', 0.20);
    bubble_core_threshold = local_get_mode_filter(Config, 'bubble_core_fraction_threshold', max(0.02, 0.50 * bubble_threshold));
    bubble_support_threshold = local_get_mode_filter(Config, 'bubble_support_fraction_threshold', bubble_threshold);
    pressure_checker_threshold_used = local_get_mode_filter(Config, 'pressure_checker_threshold', 1.5);
    if structural_only && isfield(Config.mode_filter, 'checker_threshold_structural')
        checker_threshold_used = Config.mode_filter.checker_threshold_structural;
    end
    if structural_only && isfield(Config.mode_filter, 'pressure_checker_threshold_structural')
        pressure_checker_threshold_used = Config.mode_filter.pressure_checker_threshold_structural;
    end
    pressure_free_stream_threshold = local_get_mode_filter(Config, 'pressure_free_stream_fraction_threshold', 0.35);
    pressure_outlet_threshold = local_get_mode_filter(Config, 'pressure_outlet_fraction_threshold', 0.40);
    pressure_outlet_wall_threshold = local_get_mode_filter(Config, 'pressure_outlet_wall_fraction_threshold', outlet_wall_threshold);
    pressure_shock_core_threshold = local_get_mode_filter(Config, 'pressure_shock_core_fraction_threshold', max(0.20, shock_core_threshold + 0.05));

    coupling = build_mode_coupling_audit(EigVecs, Ny, Nx, data, Config, masks, mode_metrics);
    mode_metrics.reference_component = coupling.reference_component;
    mode_metrics.family_label = coupling.family_label;
    mode_metrics.family_priority = coupling.family_priority;
    mode_metrics.physical_candidate_score = coupling.physical_candidate_score;
    mode_metrics.bubble_shock_phase_deg = coupling.bubble_shock_phase_deg;
    mode_metrics.bubble_shock_sync = coupling.bubble_shock_sync;
    mode_metrics.coupled_support_flag = coupling.coupled_support_flag;
    mode_metrics.shock_dominated_flag = coupling.shock_dominated_flag;
    mode_metrics.boundary_supported_flag = coupling.boundary_supported_flag;
    mode_metrics.compact_interior_flag = coupling.compact_interior_flag;
    is_sidharth_target = local_is_sidharth_target(Config);
    stationary_threshold = local_get_mode_filter(Config, 'stationary_frequency_threshold', 1.0e-2);
    stationary_like_mask = abs(freq_info.freq_nd_signed) <= stationary_threshold;
    w_bubble_core_overlap = local_get_component_metric(mode_metrics, 'w', 'bubble_core_overlap', zeros(num_modes, 1));
    w_bubble_support_overlap = local_get_component_metric(mode_metrics, 'w', 'bubble_support_overlap', zeros(num_modes, 1));
    w_shock_core_overlap = local_get_component_metric(mode_metrics, 'w', 'shock_core_overlap', zeros(num_modes, 1));
    w_peak_in_bubble_support = local_get_component_metric(mode_metrics, 'w', 'peak_in_bubble_support', false(num_modes, 1));
    w_peak_in_shock_core = local_get_component_metric(mode_metrics, 'w', 'peak_in_shock_core', false(num_modes, 1));
    p_checker_ratio = local_get_component_metric(mode_metrics, 'p', 'checker_ratio', zeros(num_modes, 1));
    p_free_stream_overlap = local_get_component_metric(mode_metrics, 'p', 'free_stream_overlap', zeros(num_modes, 1));
    p_outlet_overlap = local_get_component_metric(mode_metrics, 'p', 'outlet_overlap', zeros(num_modes, 1));
    p_outlet_wall_overlap = local_get_component_metric(mode_metrics, 'p', 'outlet_wall_overlap', zeros(num_modes, 1));
    p_shock_core_overlap = local_get_component_metric(mode_metrics, 'p', 'shock_core_overlap', zeros(num_modes, 1));
    p_peak_in_free_stream = local_get_component_metric(mode_metrics, 'p', 'peak_in_free_stream', false(num_modes, 1));
    p_peak_in_outlet_wall = local_get_component_metric(mode_metrics, 'p', 'peak_in_outlet_wall', false(num_modes, 1));
    p_peak_in_shock_core = local_get_component_metric(mode_metrics, 'p', 'peak_in_shock_core', false(num_modes, 1));
    reference_is_w = strcmp(coupling.reference_component, 'w');

    mask_res = residuals < Config.mode_filter.residual_threshold;
    pressure_checker_mask = p_checker_ratio < pressure_checker_threshold_used;
    pressure_localization_mask = ...
        (p_free_stream_overlap < pressure_free_stream_threshold) & ...
        (p_outlet_overlap < pressure_outlet_threshold) & ...
        (p_outlet_wall_overlap < pressure_outlet_wall_threshold) & ...
        (p_shock_core_overlap < pressure_shock_core_threshold) & ...
        ~p_peak_in_outlet_wall & ...
        ~p_peak_in_shock_core;
    if is_sidharth_target
        pressure_quality_mask = pressure_checker_mask & pressure_localization_mask;
    else
        pressure_quality_mask = pressure_checker_mask;
    end
    mask_checker = (mode_metrics.checker_ratio < checker_threshold_used) & pressure_checker_mask;
    [ranking_candidate_mask, plot_candidate_mask, selection_summary] = ...
        local_choose_candidate_masks(mask_res, mask_checker, num_modes);

    bubble_like_mask = ...
        ((mode_metrics.bubble_core_overlap > bubble_core_threshold) | ...
         (mode_metrics.bubble_support_overlap > bubble_support_threshold) | ...
         mode_metrics.u_peak_in_bubble) & ...
        (mode_metrics.near_wall_energy_frac > 0.10) & ...
        (mode_metrics.shock_energy_frac < shock_threshold) & ...
        (mode_metrics.shock_core_energy_frac < shock_core_threshold) & ...
        ~mode_metrics.u_peak_in_shock_core;

    coupled_like_mask = ...
        mode_metrics.coupled_support_flag & ...
        (mode_metrics.bubble_support_overlap > max(0.03, 0.75 * bubble_support_threshold)) & ...
        (mode_metrics.near_wall_energy_frac > 0.10) & ...
        (mode_metrics.shock_energy_frac < max(0.60, shock_threshold + 0.15)) & ...
        (mode_metrics.shock_core_energy_frac < max(0.25, shock_core_threshold + 0.08)) & ...
        ~mode_metrics.boundary_supported_flag;

    sidharth_component_mask = ...
        (w_bubble_core_overlap > max(0.01, 0.50 * bubble_core_threshold) | ...
         w_bubble_support_overlap > max(0.03, 0.60 * bubble_support_threshold) | ...
         w_peak_in_bubble_support) & ...
        (w_shock_core_overlap < max(0.25, shock_core_threshold + 0.08)) & ...
        ~w_peak_in_shock_core;
    if is_sidharth_target
        physical_support_mask = (bubble_like_mask | coupled_like_mask) & ...
            stationary_like_mask & sidharth_component_mask;
    else
        physical_support_mask = bubble_like_mask | coupled_like_mask;
    end

    publication_allowed = mask_res & ...
        physical_support_mask & ...
        (mode_metrics.free_stream_energy_frac < free_stream_threshold) & ...
        (mode_metrics.outlet_energy_frac < outlet_threshold) & ...
        (mode_metrics.outlet_wall_energy_frac < outlet_wall_threshold) & ...
        ~mode_metrics.u_peak_in_outlet_wall & ...
        (mode_metrics.checker_ratio < Config.mode_filter.checker_threshold) & ...
        pressure_quality_mask;

    sigma_r = real(EigVals);
    physical_plot_mask = plot_candidate_mask & ...
        physical_support_mask & ...
        pressure_quality_mask & ...
        (mode_metrics.free_stream_energy_frac < 0.50) & ...
        (mode_metrics.outlet_wall_energy_frac < max(0.35, outlet_wall_threshold + 0.10)) & ...
        ~mode_metrics.u_peak_in_outlet_wall & ...
        ~mode_metrics.boundary_supported_flag;
    plot_score = ...
        mode_metrics.physical_candidate_score + ...
        1.5 * double(reference_is_w) + ...
        1.5 * double(mode_metrics.u_peak_in_bubble) + ...
        8.0 * mode_metrics.bubble_core_overlap + ...
        3.0 * mode_metrics.bubble_support_overlap + ...
        7.0 * w_bubble_core_overlap + ...
        4.0 * w_bubble_support_overlap + ...
        2.0 * double(w_peak_in_bubble_support) + ...
        3.0 * mode_metrics.near_wall_energy_frac - ...
        2.5 * w_shock_core_overlap - ...
        2.5 * double(w_peak_in_shock_core) - ...
        2.5 * mode_metrics.shock_energy_frac - ...
        5.0 * mode_metrics.shock_core_energy_frac - ...
        3.0 * double(mode_metrics.u_peak_in_shock_core) - ...
        1.5 * mode_metrics.outlet_energy_frac - ...
        3.5 * mode_metrics.outlet_wall_energy_frac - ...
        2.0 * double(mode_metrics.u_peak_in_outlet_wall) - ...
        1.5 * mode_metrics.free_stream_energy_frac - ...
        0.8 * p_checker_ratio - ...
        1.2 * p_free_stream_overlap - ...
        1.0 * p_outlet_overlap - ...
        2.5 * p_outlet_wall_overlap - ...
        2.0 * p_shock_core_overlap - ...
        1.5 * double(p_peak_in_free_stream) - ...
        2.5 * double(p_peak_in_outlet_wall) - ...
        2.0 * double(p_peak_in_shock_core) - ...
        0.2 * mode_metrics.checker_ratio - ...
        1.0e3 * residuals + ...
        0.1 * sigma_r;
    rank_keys = table( ...
        ~physical_plot_mask, ...
        ~ranking_candidate_mask, ...
        ~physical_support_mask, ...
        mode_metrics.family_priority, ...
        ~stationary_like_mask, ...
        ~sidharth_component_mask, ...
        ~mode_metrics.u_peak_in_bubble, ...
        mode_metrics.u_peak_in_shock_core, ...
        mode_metrics.u_peak_in_outlet_wall, ...
        -plot_score, ...
        -mode_metrics.bubble_core_overlap, ...
        -w_bubble_core_overlap, ...
        -mode_metrics.bubble_support_overlap, ...
        -w_bubble_support_overlap, ...
        -mode_metrics.near_wall_energy_frac, ...
        w_shock_core_overlap, ...
        mode_metrics.shock_core_energy_frac, ...
        mode_metrics.outlet_wall_energy_frac, ...
        mode_metrics.shock_energy_frac, ...
        mode_metrics.free_stream_energy_frac, ...
        residuals, ...
        mode_metrics.checker_ratio, ...
        -sigma_r, ...
        (1:num_modes).', ...
        'VariableNames', {'k0', 'k1', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8', 'k9', 'k10', 'k11', ...
        'k12', 'k13', 'k14', 'k15', 'k16', 'k17', 'k18', 'k19', 'k20', 'k21', 'k22', 'k23'});
    [~, order] = sortrows(rank_keys, {'k0', 'k1', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8', 'k9', 'k10', ...
        'k11', 'k12', 'k13', 'k14', 'k15', 'k16', 'k17', 'k18', 'k19', 'k20', 'k21', 'k22', 'k23'});

    n_keep = min(numel(order), max(4, round(Config.n_eigs)));
    order = order(1:n_keep);
    selected_for_plots = false(n_keep, 1);
    plot_pool = find(physical_plot_mask(order));
    if ~isempty(plot_pool)
        plot_pool = plot_pool(1:min(4, numel(plot_pool)));
        selected_for_plots(plot_pool) = true;
    end

    ranking = struct();
    ranking.order = order;
    ranking.freq_info = freq_info;
    ranking.ModeDiag = ModeDiag(order);
    ranking.legacy_rejection_tags = legacy_rejection_tags(order);
    ranking.plot_candidate_mask = plot_candidate_mask(order);
    ranking.publication_allowed = publication_allowed(order);
    ranking.selected_for_plots = selected_for_plots;
    ranking.selection_summary = selection_summary;
    ranking.selection_summary.checker_threshold_used = checker_threshold_used;
    ranking.selection_summary.pressure_checker_threshold_used = pressure_checker_threshold_used;
    ranking.selection_summary.pressure_free_stream_threshold = pressure_free_stream_threshold;
    ranking.selection_summary.pressure_outlet_threshold = pressure_outlet_threshold;
    ranking.selection_summary.pressure_outlet_wall_threshold = pressure_outlet_wall_threshold;
    ranking.selection_summary.pressure_shock_core_threshold = pressure_shock_core_threshold;
    ranking.selection_summary.num_plot_candidates = nnz(plot_candidate_mask);
    ranking.selection_summary.num_ranking_candidates = nnz(ranking_candidate_mask);
    ranking.selection_summary.num_physical_plot_candidates = nnz(physical_plot_mask);
    ranking.selection_summary.num_selected_modes = nnz(selected_for_plots);
    ranking.selection_summary.structural_only = structural_only;
    ranking.selection_summary.num_coupled_candidates = nnz(coupled_like_mask & plot_candidate_mask);
    ranking.selection_summary.num_bubble_candidates = nnz(bubble_like_mask & plot_candidate_mask);
    ranking.selection_summary.target_benchmark = local_get_target_benchmark(Config);
    ranking.selection_summary.num_sidharth_component_candidates = nnz(sidharth_component_mask & plot_candidate_mask);
    ranking.selection_summary.num_stationary_candidates = nnz(stationary_like_mask & plot_candidate_mask);
    ranking.selection_summary.num_pressure_checker_candidates = nnz(pressure_checker_mask & plot_candidate_mask);
    ranking.selection_summary.num_pressure_quality_candidates = nnz(pressure_quality_mask & plot_candidate_mask);
    ranking.selection_summary.plot_fallback_used = ...
        any(plot_candidate_mask) && ~any(mask_res & mask_checker);
    if any(selected_for_plots)
        ranking.selection_summary.status = 'physical_plot_candidates_available';
        ranking.selection_summary.plot_status = 'physical_plot_candidates_available';
    else
        ranking.selection_summary.status = 'no_physical_plot_candidates';
        ranking.selection_summary.plot_status = 'no_physical_plot_candidates';
    end
    ranking.metrics = local_slice_metrics(mode_metrics, order);
    ranking.residuals = residuals(order);
    ranking.residuals_active = residuals_active(order);
    ranking.residuals_algebraic = residuals_algebraic(order);
    ranking.residuals_scaled = residuals_scaled(order);
    ranking.EigVals = EigVals(order);
    ranking.EigVecs = EigVecs(:, order);
    ranking.original_mode_index = order(:);
    ranking.farfield_ratio = farfield_ratio(order);
    ranking.highfreq_ratio = highfreq_ratio(order);
    ranking.ranking_table = table( ...
        ranking.original_mode_index, real(ranking.EigVals), imag(ranking.EigVals), ranking.residuals, ...
        ranking.residuals_active, ranking.residuals_algebraic, ranking.residuals_scaled, ...
        ranking.freq_info.freq_nd_abs(order), ranking.freq_info.freq_nd_signed(order), ...
        ranking.metrics.bubble_overlap, ranking.metrics.bubble_core_overlap, ...
        ranking.metrics.bubble_support_overlap, ranking.metrics.wall_energy_frac, ...
        ranking.metrics.near_wall_energy_frac, ranking.metrics.free_stream_energy_frac, ...
        ranking.metrics.sponge_energy_frac, ranking.metrics.shock_energy_frac, ...
        ranking.metrics.shock_core_energy_frac, ...
        ranking.metrics.outlet_energy_frac, ranking.metrics.outlet_wall_energy_frac, ...
        ranking.metrics.corner_energy_frac, ranking.metrics.bad_point_energy_frac, ...
        ranking.metrics.checker_ratio, ranking.metrics.u_peak_in_bubble, ...
        ranking.metrics.p_checker_ratio, ranking.metrics.p_free_stream_overlap, ...
        ranking.metrics.p_outlet_overlap, ranking.metrics.p_outlet_wall_overlap, ...
        ranking.metrics.p_shock_core_overlap, ranking.metrics.p_peak_in_free_stream, ...
        ranking.metrics.p_peak_in_outlet_wall, ranking.metrics.p_peak_in_shock_core, ...
        ranking.metrics.u_peak_in_shock_core, ranking.metrics.u_peak_in_outlet_wall, ...
        ranking.metrics.u_peak_in_corner, ranking.metrics.u_peak_in_bad_point, ...
        ranking.farfield_ratio, ranking.highfreq_ratio, ranking.metrics.physical_candidate_score, ...
        ranking.metrics.bubble_shock_phase_deg, ranking.metrics.bubble_shock_sync, ...
        ranking.metrics.family_label, ranking.plot_candidate_mask, ...
        ranking.publication_allowed, ranking.selected_for_plots, ...
        'VariableNames', {'mode_index', 'sigma_r', 'sigma_i', 'residual', ...
        'residual_active', 'residual_algebraic', 'residual_scaled', ...
        'freq_nd', 'freq_signed', 'bubble_overlap', 'bubble_core_overlap', ...
        'bubble_support_overlap', 'wall_energy_frac', ...
        'near_wall_energy_frac', 'free_stream_energy_frac', 'sponge_energy_frac', ...
        'shock_energy_frac', 'shock_core_energy_frac', 'outlet_energy_frac', 'outlet_wall_energy_frac', ...
        'corner_energy_frac', 'bad_point_energy_frac', ...
        'checker_ratio', 'u_peak_in_bubble', ...
        'p_checker_ratio', 'p_free_stream_overlap', 'p_outlet_overlap', ...
        'p_outlet_wall_overlap', 'p_shock_core_overlap', 'p_peak_in_free_stream', ...
        'p_peak_in_outlet_wall', 'p_peak_in_shock_core', ...
        'u_peak_in_shock_core', 'u_peak_in_outlet_wall', ...
        'u_peak_in_corner', 'u_peak_in_bad_point', ...
        'farfield_energy_ratio', 'highfreq_uv', 'physical_candidate_score', ...
        'bubble_shock_phase_deg', 'bubble_shock_sync', 'mode_family', 'plot_candidate', ...
        'selected_for_publication', 'selected_for_plots'});
end

function value = local_get_mode_filter(Config, field_name, default_value)
%LOCAL_GET_MODE_FILTER Return one mode-filter threshold with backward compatibility.

    value = default_value;
    if isfield(Config, 'mode_filter') && isstruct(Config.mode_filter) && ...
            isfield(Config.mode_filter, field_name)
        value = Config.mode_filter.(field_name);
    end
end

function metrics_out = local_slice_metrics(metrics_in, order)
%LOCAL_SLICE_METRICS Slice all metric vectors using one common order.

    metrics_out = struct();
    names = fieldnames(metrics_in);
    for k = 1:numel(names)
        name = names{k};
        value = metrics_in.(name);
        if isstruct(value)
            metrics_out.(name) = local_slice_metrics(value, order);
        elseif ((isnumeric(value) || islogical(value) || iscell(value) || isstring(value)) && ...
                isvector(value) && numel(value) >= max(order))
            metrics_out.(name) = value(order);
        else
            metrics_out.(name) = value;
        end
    end
end

function [ranking_candidate_mask, plot_candidate_mask, summary] = local_choose_candidate_masks(mask_res, mask_checker, num_modes)
%LOCAL_CHOOSE_CANDIDATE_MASKS Separate debug ranking fallbacks from true plot eligibility.

    if any(mask_res & mask_checker)
        ranking_candidate_mask = mask_res & mask_checker;
        plot_candidate_mask = mask_res & mask_checker;
        ranking_status = 'residual_checker_modes';
        reason = '';
    elseif any(mask_res)
        ranking_candidate_mask = mask_res;
        plot_candidate_mask = mask_res;
        ranking_status = 'residual_only_fallback';
        reason = 'no mode passed the active checker threshold';
    else
        ranking_candidate_mask = true(num_modes, 1);
        plot_candidate_mask = false(num_modes, 1);
        ranking_status = 'debug_all_modes_fallback';
        reason = 'no mode passed the residual threshold';
    end

    summary = struct();
    summary.status = 'no_physical_plot_candidates';
    summary.ranking_status = ranking_status;
    summary.relaxed_reason = reason;
    summary.ranking_relaxed_reason = reason;
    summary.num_input_modes = num_modes;
    summary.num_residual_modes = nnz(mask_res);
    summary.num_checker_modes = nnz(mask_res & mask_checker);
    summary.num_plot_pool_modes = nnz(plot_candidate_mask);
end

function value = local_get_component_metric(mode_metrics, component_name, field_name, default_value)
%LOCAL_GET_COMPONENT_METRIC Read one component-specific metric vector with fallback.

    value = default_value;
    if isstruct(mode_metrics) && isfield(mode_metrics, 'component_support') && ...
            isstruct(mode_metrics.component_support) && isfield(mode_metrics.component_support, component_name)
        component_metrics = mode_metrics.component_support.(component_name);
        if isstruct(component_metrics) && isfield(component_metrics, field_name)
            value = component_metrics.(field_name);
        end
    end
end

function tf = local_is_sidharth_target(Config)
%LOCAL_IS_SIDHARTH_TARGET True when ranking should obey the Sidharth contract.

    tf = strcmpi(local_get_target_benchmark(Config), 'Sidharth2018');
end

function target = local_get_target_benchmark(Config)
%LOCAL_GET_TARGET_BENCHMARK Read the active benchmark target from Config.

    target = '';
    if isstruct(Config) && isfield(Config, 'target_benchmark')
        target = char(string(Config.target_benchmark));
    elseif isstruct(Config) && isfield(Config, 'benchmark') && isstruct(Config.benchmark) && ...
            isfield(Config.benchmark, 'target_benchmark')
        target = char(string(Config.benchmark.target_benchmark));
    end
end
