function [lead_plot_idx, audit] = select_paperA_plot_lead_index(ranking)
%SELECT_PAPERA_PLOT_LEAD_INDEX Pick the default leading mode used for figure output.

    num_modes = numel(ranking.EigVals);
    lead_plot_idx = NaN;
    audit = struct('status', 'no_modes', 'candidate_count', 0, ...
        'candidate_source', 'none', 'used_selected_for_plots_only', false);
    if num_modes <= 0
        return;
    end

    metrics = ranking.metrics;
    if isfield(ranking, 'plot_lead_candidate_mask') && ~isempty(ranking.plot_lead_candidate_mask)
        indices = find(ranking.plot_lead_candidate_mask);
        audit.candidate_source = 'plot_lead_candidate_mask';
        audit.used_selected_for_plots_only = false;
    else
        indices = find(ranking.selected_for_plots);
        audit.candidate_source = 'selected_for_plots';
        audit.used_selected_for_plots_only = true;
    end
    audit.candidate_count = numel(indices);
    if isempty(indices)
        audit.status = 'no_physical_plot_candidate';
        return;
    end
    audit.status = 'physical_plot_candidate';

    family_priority = local_metric_or_default(metrics, 'family_priority', zeros(num_modes, 1));
    physical_score = local_metric_or_default(metrics, 'physical_candidate_score', zeros(num_modes, 1));
    w_bubble_support = local_component_metric_or_default(metrics, 'w', 'bubble_support_overlap', zeros(num_modes, 1));
    w_bubble_core = local_component_metric_or_default(metrics, 'w', 'bubble_core_overlap', zeros(num_modes, 1));
    w_shock_core = local_component_metric_or_default(metrics, 'w', 'shock_core_overlap', zeros(num_modes, 1));
    w_peak_in_bubble = local_component_metric_or_default(metrics, 'w', 'peak_in_bubble_support', false(num_modes, 1));
    w_peak_in_shock = local_component_metric_or_default(metrics, 'w', 'peak_in_shock_core', false(num_modes, 1));
    p_checker = local_component_metric_or_default(metrics, 'p', 'checker_ratio', ...
        local_metric_or_default(metrics, 'p_checker_ratio', zeros(num_modes, 1)));
    p_free_stream = local_component_metric_or_default(metrics, 'p', 'free_stream_overlap', ...
        local_metric_or_default(metrics, 'p_free_stream_overlap', zeros(num_modes, 1)));
    p_outlet = local_component_metric_or_default(metrics, 'p', 'outlet_overlap', ...
        local_metric_or_default(metrics, 'p_outlet_overlap', zeros(num_modes, 1)));
    p_outlet_wall = local_component_metric_or_default(metrics, 'p', 'outlet_wall_overlap', ...
        local_metric_or_default(metrics, 'p_outlet_wall_overlap', zeros(num_modes, 1)));
    p_shock_core = local_component_metric_or_default(metrics, 'p', 'shock_core_overlap', ...
        local_metric_or_default(metrics, 'p_shock_core_overlap', zeros(num_modes, 1)));
    p_peak_in_free_stream = local_component_metric_or_default(metrics, 'p', 'peak_in_free_stream', ...
        local_metric_or_default(metrics, 'p_peak_in_free_stream', false(num_modes, 1)));
    p_peak_in_outlet_wall = local_component_metric_or_default(metrics, 'p', 'peak_in_outlet_wall', ...
        local_metric_or_default(metrics, 'p_peak_in_outlet_wall', false(num_modes, 1)));
    p_peak_in_shock_core = local_component_metric_or_default(metrics, 'p', 'peak_in_shock_core', ...
        local_metric_or_default(metrics, 'p_peak_in_shock_core', false(num_modes, 1)));
    u_peak_in_bubble = local_metric_or_default(metrics, 'u_peak_in_bubble', false(num_modes, 1));
    u_peak_in_shock_core = local_metric_or_default(metrics, 'u_peak_in_shock_core', false(num_modes, 1));
    u_peak_in_outlet_wall = local_metric_or_default(metrics, 'u_peak_in_outlet_wall', false(num_modes, 1));
    score = -inf(num_modes, 1);
    score(indices) = ...
        physical_score(indices) - ...
        2.0 * family_priority(indices) + ...
        1.5 * w_bubble_support(indices) + ...
        2.5 * w_bubble_core(indices) + ...
        1.5 * double(w_peak_in_bubble(indices)) + ...
        1.0 * double(u_peak_in_bubble(indices)) + ...
        6.0 * metrics.bubble_core_overlap(indices) + ...
        2.0 * metrics.bubble_support_overlap(indices) + ...
        2.5 * metrics.near_wall_energy_frac(indices) - ...
        2.5 * w_shock_core(indices) - ...
        2.0 * double(w_peak_in_shock(indices)) - ...
        3.0 * metrics.shock_energy_frac(indices) - ...
        5.0 * metrics.shock_core_energy_frac(indices) - ...
        3.0 * double(u_peak_in_shock_core(indices)) - ...
        2.0 * metrics.outlet_energy_frac(indices) - ...
        4.0 * metrics.outlet_wall_energy_frac(indices) - ...
        2.5 * double(u_peak_in_outlet_wall(indices)) - ...
        1.5 * metrics.free_stream_energy_frac(indices) - ...
        0.8 * p_checker(indices) - ...
        1.2 * p_free_stream(indices) - ...
        1.0 * p_outlet(indices) - ...
        2.5 * p_outlet_wall(indices) - ...
        2.0 * p_shock_core(indices) - ...
        1.5 * double(p_peak_in_free_stream(indices)) - ...
        2.5 * double(p_peak_in_outlet_wall(indices)) - ...
        2.0 * double(p_peak_in_shock_core(indices)) - ...
        0.8 * metrics.checker_ratio(indices) - ...
        1.0e3 * ranking.residuals(indices) + ...
        0.02 * real(ranking.EigVals(indices));
    [~, lead_plot_idx] = max(score);
end

function value = local_metric_or_default(metrics, field_name, default_value)
%LOCAL_METRIC_OR_DEFAULT Optional ranking metric helper.

    if isstruct(metrics) && isfield(metrics, field_name)
        value = metrics.(field_name);
    else
        value = default_value;
    end
end

function value = local_component_metric_or_default(metrics, component_name, field_name, default_value)
%LOCAL_COMPONENT_METRIC_OR_DEFAULT Optional nested component-metric helper.

    value = default_value;
    if isstruct(metrics) && isfield(metrics, 'component_support') && ...
            isstruct(metrics.component_support) && isfield(metrics.component_support, component_name)
        component_metrics = metrics.component_support.(component_name);
        if isstruct(component_metrics) && isfield(component_metrics, field_name)
            value = component_metrics.(field_name);
        end
    end
end
